Changes to Set Woocommerce Payment Method to 'Paypal' only if transac…
CodistoConnect/CodistoConnect-WooCommerce pull request #89
Opened 2020-10-20 03:12 UTC by bhushan-mehta

…tionid is exist and Payment method is Paypal

2020-10-20 03:35 UTC, jschiller commented on connect.php
> +							if ( $transaction_id  && $paymentmethod == "paypal") {
Not quite. We need a regular expression here as we may send "paypal" or "paypalec", so please make this match on regular expression containing paypal.

2020-10-20 03:35 UTC, jschiller commented on connect.php
> +							if ( $transaction_id  && $paymentmethod == "paypal") {
Same as above

2020-10-20 04:33 UTC, bhushan-mehta commented on connect.php
> +							if ( $transaction_id  && $paymentmethod == "paypal") {
Regex expression added

2020-10-20 04:33 UTC, bhushan-mehta commented on connect.php
> +							if ( $transaction_id  && $paymentmethod == "paypal") {
Regex expression added

2020-10-23 03:07 UTC, jlivas requested changes

2020-10-23 03:07 UTC, jlivas commented on connect.php
> +							if ( $transaction_id  && preg_match('/^(?:paypal|paypal[a-zA-Z]+)$/i',$paymentmethod)) {
I think we can loosen this regex to just look for anything with 'paypal' in the string

2020-10-23 03:07 UTC, jlivas commented on connect.php
> +							if ( $transaction_id  && preg_match('/^(?:paypal|paypal[a-zA-Z]+)$/i',$paymentmethod)) {
I think we can loosen this regex to just look for anything with 'paypal' in the string

2020-10-26 05:44 UTC, bhushan-mehta commented on connect.php
> +							if ( $transaction_id  && preg_match('/^(?:paypal|paypal[a-zA-Z]+)$/i',$paymentmethod)) {
DONE

2020-10-26 05:44 UTC, bhushan-mehta commented on connect.php
> +							if ( $transaction_id  && preg_match('/^(?:paypal|paypal[a-zA-Z]+)$/i',$paymentmethod)) {
DONE

2020-11-30 01:36 UTC, merged